# Generated by Django 3.0.3 on 2020-02-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200216_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='art_imgs/', verbose_name='imagen para el artículo'),
        ),
    ]
